---
apiVersion: v1
kind: Secret
metadata:
  name: lookmyshow-db-secret
  namespace: default
stringData:
  DB_USER: lookmyshow_app
  DB_PASSWORD: "YOUR_DB_PASSWORD" # Replace with actual or use kubectl create secret
  DB_NAME: eventsdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lookmyshow-db-config
  namespace: default
  labels:
    app: lookmyshow-app
data:
  DB_HOST: "YOUR_DB_HOST" # Set to Cloud SQL private IP or use a Service name if using proxy 