clusterName: CLUSTER-NAME
region: us-east-1
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  name: aws-load-balancer-controller 

replicaCount: 2
image:
  repository: public.ecr.aws/eks/aws-load-balancer-controller
  tag: v2.7.2
  pullPolicy: IfNotPresent
