trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '<AzureServiceConnectionName>'
  resourceGroup: 'ade-sandbox-rg'
  webAppName: 'StaticWebApp'
  location: 'East US'

stages:
  - stage: DeployInfrastructure
    jobs:
      - job: Deploy
        steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create \
                  --resource-group $(resourceGroup) \
                  --template-file infra/main.bicep \
                  --parameters location="$(location)"

  - stage: DeployWebsite
    jobs:
      - job: Deploy
        steps:
          - checkout: self
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'website'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/website.zip'
              replaceExistingArchive: true

          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              package: '$(Build.ArtifactStagingDirectory)/website.zip'
              runtimeStack: 'DOTNETCORE|6.0'
              enableCustomDeployment: true
              enableWebJobs: true
              enableContinuousDeployment: true
              enableAppInsights: true
              enableAppService: true
              enableStaticWebApp: true
              enableStaticWebAppPreview: true
              enableStaticWebAppPreviewBranch: true
              enableStaticWebAppPreviewEnvironment: true
              enableStaticWebAppPreviewEnvironmentName: 'preview'
              enableStaticWebAppPreviewEnvironmentUrl: 'https://$(webAppName).azurestaticapps.net'
