# This playbook uses roles to install AWS CLI and Docker on all nodes and build and push Docker image on the Ansible controller.
---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - common

- hosts: localhost
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - docker_build