# This file is part of the Movie App opensource project. This will be used to build and push the Docker image to AWS ECR.
- name: Build Docker image
  shell: |
    cd ../docker
    bash ./build.sh {{ aws_region }} {{ aws_account_id }} {{ movie_client_repo }} {{ movie_server_repo }}

- name: Tag Docker image
  shell: |
    sudo docker tag jenkins-docker:latest {{ ecr_registry }}/{{ jenkins_repo }}:latest

- name: Push Docker image to ECR
  shell: |
    sudo docker push {{ ecr_registry }}/{{ jenkins_repo }}:latest