# This playbook uses roles to install AWS CLI and Docker on all nodes and build and push Docker image on the Ansible controller, while adding docker compose to app nodes
---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - common

- hosts: localhost
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - docker_build

- hosts: name_dev_app_*
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - docker_compose