pipeline {
    agent any

//   environment {
//     SSH_KEY = credentials('app-instance-key') // Replace with the ID of the SSH key credential in Jenkins
//    }

    stages {
        stage('SSH to App Hosts') {
            steps {
                script {
                    // Define the list of app hosts
                    def appHosts = ['10.1.1.95', '10.1.2.213'] // Replace with the actual IPs of the app instances

                    // Iterate over the app hosts and run commands on each
                    for (host in appHosts) {
                        sshagent(credentials: ['app-instance-key']) {
                            sh """
                                ssh -o StrictHostKeyChecking=no ubuntu@${host} 'echo "Hello from Jenkins on ${host}"'
                            """
                        }
                    }
                }
            }
        }
    }
}
