services:
  client:
    image: movies-client:latest
    container_name: client
    ports:
     - "8000:8000"
    networks:
     - front-tier 

  server:
    image: movies-server:latest
    container_name: server
    ports:
     - "3000:3000"
    networks:
     - back-tier
     - front-tier

  mongo:
     image: mongo
     container_name: mongodb
     environment:
       - PUID=1000
       - PGID=1000
     volumes:
        - /home/ubuntu/mongodb/database:/data/db
     networks:
      - back-tier

networks:
    front-tier:
    back-tier:
