runtime: python39

env_variables:
  DB_HOST: "104.198.208.198"
  DB_USER: "root"
  DB_PASSWORD: "M7rk|(`J&H1+*I>i"
  DB_NAME: "eventsdb"
  DB_PORT: "3306"
  API_HOST: "0.0.0.0"
  API_PORT: "8080"
  DEBUG: "false"
  CORS_ORIGINS: "*"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /api/.*
  script: auto

- url: /static
  static_dir: static

- url: /.*
  static_files: index.html
  upload: index.html 